# Generated by Django 2.1 on 2018-12-25 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_open', models.BooleanField(default=True, verbose_name='Is Open')),
                ('is_release', models.BooleanField(default=True, verbose_name='Is Release')),
                ('is_permission', models.BooleanField(default=True, verbose_name='Is Permission')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('editor', models.CharField(choices=[('edit.md', 'edit.md'), ('wangEdit', 'wangEdit')], default='Inactive', max_length=32)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='Modify Time')),
                ('version', models.CharField(max_length=32, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('is_permission', models.BooleanField(default=True, verbose_name='Permission')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='Modify Time')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('str_id', models.IntegerField()),
                ('sort_id', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True, verbose_name='Article content')),
                ('markdown', models.TextField(blank=True, null=True, verbose_name='Content of Markdown')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Content of Html')),
                ('version', models.CharField(max_length=128, verbose_name='Version')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is Open')),
                ('is_release', models.BooleanField(default=True, verbose_name='Is Release')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='Modify Time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='min_doc.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='min_doc.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
