# Generated by Django 2.1 on 2019-01-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('min_doc', '0003_auto_20190102_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
    ]
