# Generated by Django 2.1 on 2019-01-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min_doc', '0004_remove_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password2',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32, verbose_name='Status'),
        ),
    ]
